---
# Install and configure application code

- name: install supervisor
  apt: name=supervisor state=present

- name: install pip
  apt: name=python-pip state=present

- name: install gunicorn
  pip: name=gunicorn

- name: install tamales
  pip: name='https://github.com/Antojitos/tamales/archive/{{ tamales_version }}.tar.gz'
  notify: restart supervisor

- name: create configuration file for supervisor
  template: src=supervisor-tamales.conf.j2 dest=/etc/supervisor/conf.d/tamales.conf
  notify: update supervisor
